sudo: required
dist: xenial

install:
  - sudo apt install -y software-properties-common
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt update -qq
  - sudo apt install -y solc

script:
  - |
    status=0
    for file in *.sol; do
      solc --combined-json abi,bin $file > /dev/null
      if [ $? -ne 0 ]; then status=1; fi
    done
    exit $status
